version: "3.9"
services:
  flask-app:
    build:
      context: .  # Директория, где находится Dockerfile
    ports:
      - "5000:5000"  # Проброс порта 5000 на хост. Изменяемый
    volumes:
      - .:/app  # Монтирование текущей директории внутрь контейнера
